### ISSUE TITLE
Add a supported way to limit buffer size

### ISSUE THREAD

**Issue by mmarchini** [pinojs/sonic-boom#117]
We've been facing some memory issues which we tracked down to be really huge sonic-boom buffers. To prevent this kind of issue, it would be nice if sonic-boom provided a way to limit the buffer size when running on async mode. Are there any preferences on how such a feature would be implemented? I could see it being implemented as a maxLength option that drops anything new if the buffer length goes past it, or as an optional handler function that allows developers to implement custom dropping logic. Personally I think I prefer maxLength.

I'm happy to implement it if this is something others would be interested on.

**Comment by mcollina** [comment]
Go for it! I I would adding this logic in https://github.com/pinojs/sonic-boom/blob/2edc3ae41fdc5269ed2038b4acb2cc71482e4cff/index.js#L225.

**Comment by mmarchini** [comment]
Ok, I'll start implementing it as the second option (handler function for custom dropping logic).

**Comment by mcollina** [comment]
I'm sorry, go for maxLenght!

**Comment by mmarchini** [comment]
Fixed in #119
