### ISSUE TITLE
Add mkdir (or mkdirs) option to ensure directory of dest file exists

### ISSUE THREAD

**Issue by mojavelinux** [pinojs/sonic-boom#78]
Users of my application, which uses pino for logging, want to be able to create the log file in a directory which does not already exist. Currently, pino can only create a log file in a directory which exists because SonicBoom doesn't check for the existence of the directory. As a result, the onus falls on the application to create the directory before instantiating pino (and hence SonicBoom).

This situation is less than ideal because the application has to inspect the logging options, determine if there is a file to create, do the work of ensuring the directory exists (creating it if necessary), and handle any errors that comes from it. (If the function that instantiates the logger is not an async function, this has to be done using a sync fs call).

I'm proposing to make this behavior configurable, controlled by a new `mkdirs` option (or `mkdir`?). If the value of the option is false or undefined, SonicBoom will not check for the existence of the directory (the existing behavior). If the value of the option is true, SonicBoom will ensure the directory exists before opening the file.

Here's how this option would be used:

```
new SonicBoom({ dest: 'logs/application.log', mkdirs: true })
```

I'm also open to the idea of just making this the default behavior. (To cite a well-established precedent, vinyl-fs dest will create the target directory if it does not exist).

I will do the work of submitting a PR with tests to implement it.

**Comment by mojavelinux** [comment]
I'm contemplating three questions:

* Should this just be the default (non-configurable) behavior?
* If we decide to make it configurable, should the option be named `mkdir` instead of `mkdirs`?
* Should we skip this check on a call to `reopen()`? (It's possible the directory no longer exists, but that's an unlikely scenario)

**Comment by jsumners** [comment]
I think this is very likely to cross the responsibility boundary. I think this module should expect that the destination file exists. As the follow up post suggests, there are at least a few error states to consider when the file does not already exist and it seems to me like handling that would be application specific logic.

**Comment by mojavelinux** [comment]
The destination file exists? That seems highly unlikely for a log file, especially if the user is providing the path. The whole point of specifying the destination file is to create it. And that's, in fact, what SonicBoom currently does. What it doesn't do, is ensure it can create it.

> there are at least a few error states to consider when the file does not already exist

I don't think we have to worry about that. If the directory is not writable, the file cannot be created. SonicBoom already handles that case. If the directory cannot be created, then it's really the same situation. I don't see this as much of a responsibility change in SonicBoom. It's all part of creating the fille and handling the error if that atomic operation fails.

> As the follow up post suggests

Which post are you referring to?

> it seems to me like handling that would be application specific logic.

I'll reiterate my point in the append option issue to emphasize why this is not tenable:

> From #76
> If the function that instantiates the logger is not an async function, this has to be done using a sync fs call. That complexity could be somewhat mitigated if there were a hook in SonicBoom before the file is opened, but there's currently no such hook.

So SonicBoom is not providing an opportunity to hook into the file open process. Without that, I argue it really does need to be done by SonicBoom.

**Comment by mcollina** [comment]
I don't feel this is the responsibility of SonicBoom. This is very simple to achieve _outside_ of SonicBoom just by adding a call to `mkdirp` https://www.npmjs.com/package/mkdirp just before calling the destination.

In order to mitigate this concern, we might want to do a call to `fs.accessSync()` when we instantiating the stream so that it throws synchronously and it could potentially be caught and act upon.

**Comment by kibertoad** [comment]
@mcollina Why even use mkdirp if Node supports recursive mkdir natively these days?

**Comment by mojavelinux** [comment]
@mcollina That doesn't address my point that there is no good point in the application to do this work. We at least need a hook that allows for the application to plug in code before the file is opened to set the stage. Otherwise, the application has to add all this code in front of the call to pino to inspect the options and determine if a directory has to be created. And if the file has to be created async, that forces the caller to be async as well, which fundamentally changes the contract with pino.

**Comment by mojavelinux** [comment]
> Why even use mkdirp if Node supports recursive mkdir natively these days?

Exactly. The call would be `fs.mkdir|mkdirSync(path.dirname(file), { recursive: true })`
