### ISSUE TITLE
What Changes are Breaking for v1 -> v2?

### ISSUE THREAD

**Issue by aphix** [pinojs/sonic-boom#88]
Forgive me if I just missed it, but in looking to update some deps I see that this has been bumped to v2+ and I don't see the breaking changes listed anywhere, so figured I'd create an issue to ask what they may be (and to perhaps get them documented).

Cheers, and thanks for the great module.

**Comment by kibertoad** [comment]
https://github.com/pinojs/sonic-boom/pull/66 and https://github.com/pinojs/sonic-boom/pull/45 (note that TS types are not compatible with DT ones).

**Comment by aphix** [comment]
Assuming I'm already on Node v12 and up, is there any functional/usage difference that would result from the `flatstr` removal?

Thanks for the quick reply!

**Comment by kibertoad** [comment]
@aphix Yes. Your performance might improve. See https://github.com/davidmarkclements/flatstr/issues/10

**Comment by aphix** [comment]
@kibertoad So, no changes from me and a potential performance boost? Awesome! That's a rare and nice thing to hear =)

Thanks again, closing-
